### ISSUE TITLE
Computer Information.bash needs change to support 10.14

### ISSUE THREAD

**Issue by Honestpuck** [talkingmoose/Casper-Scripts#4]
The line 

`
runCommand=$( /usr/sbin/ioreg -r -c "AppleSmartBattery" | /usr/bin/grep -w "CycleCount" | /usr/bin/awk '{print $3}' | /usr/bin/sed s/\"//g )
`

does not work in 10.14. 

The `grep` returns more than one line. Change it to 
`grep ' "CycleCount'` 
and it will only return the correct line and the dialog will display the correct information. Yes, that is a single quote followed by a space, followed by a double quote, followed by the text :)

This change has also been tested in 10.13.2

**Comment by talkingmoose** [comment]
My customer found this issue too. We ended up changing that line to this:

`ioreg -r -c "AppleSmartBattery" | grep '"CycleCount" = ' | awk '{ print $3 }' | sed s/\"//g`

I'll update the script with this.
